# Exercise 1: Creating Numpy Arrays

At the core of NumPy is the ndarray, where nd stands for n-dimensional. An ndarray is a multidimensional array of elements all of the same type. 

Check size, shape, type and dtype for all the below:

1) Create 1D array containing integers

2) Create 1D array containing strings

3) Create 2D array containing integers

4) Create 1D array containing float and integers - Understand Upcasting

5) Create an array and fix the dtype to int64

6) Save and load numpy array using np.save() and np.load()

https://docs.scipy.org/doc/numpy/user/basics.creation.html

In [163]:
import numpy as np

In [177]:
x=np.array([5,6,8,9.54])
np.save('new',x)

x.dtype

dtype('float64')

In [178]:
np.load('new.npy')

array([5.  , 6.  , 8.  , 9.54])

# Exercise 2: Using Built-in functions to Create ndarrays

shape in the form (rows, columns)

1) Zero array or matrix - Use np.zeros(shape) 

2) array or matrix of ones - Use np.ones(shape)

3) array or matrix of specific number - Use np.full(shape, number) 

4) identity matrix - Use np.eye(matrix-size)

5) diagonal matrix - Use np.diag([list])


In [186]:
x=np.diag([4,5,6,6])
print(x)
x.dtype

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 6]]


dtype('int32')

# Exercise 3:

Create a 4x5 matrix with first column as ones, second as only 2's, third as 3's .. and so on. 

Sample Output: 
([[1., 2., 3., 4., 5.],
  [1., 2., 3., 4., 5.],
  [1., 2., 3., 4., 5.],
  [1., 2., 3., 4., 5.]])

In [188]:
np.ones((4,5))*np.arange(1,6)

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

# Exercise 4: Using Built-in function - arange, linspace : To create one dimensional array

**np.arange**

np.arange() allows you to create ndarrays that have evenly spaced values within a given interval.This function is very versatile and can be used with either one, two, or three arguments. 

a) np.arange(N)

b) np.arange(start,stop)

c) np.arange(start,stop,step)

**np.linspace()**

np.linspace(start, stop, N) function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values.

np.linspace(start, stop, spacing, endpoint=True/False)

In [193]:
np.linspace(2,10,15,endpoint=False)

array([2.        , 2.53333333, 3.06666667, 3.6       , 4.13333333,
       4.66666667, 5.2       , 5.73333333, 6.26666667, 6.8       ,
       7.33333333, 7.86666667, 8.4       , 8.93333333, 9.46666667])

# Exercise 4: Using Built-in function - reshape : To create Two dimensional array


**np.arange**

np.arange(10).reshape(2,5)

or

np.reshape(x, (row,columns))



In [197]:
np.linspace(1,20,50).reshape(10,5)

array([[ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041],
       [ 2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592],
       [ 4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143],
       [ 6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694],
       [ 8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245],
       [10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796],
       [12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347],
       [14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898],
       [16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449],
       [18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ]])

# Exercise 5: 

Create a matrix of 6 x 4 dimensions, with each element as a multiple of 3.

sample output:

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60],
       [63, 66, 69, 72]])

In [199]:
np.linspace(3,72,24).reshape(6,4)

array([[ 3.,  6.,  9., 12.],
       [15., 18., 21., 24.],
       [27., 30., 33., 36.],
       [39., 42., 45., 48.],
       [51., 54., 57., 60.],
       [63., 66., 69., 72.]])

# Exercise 6: Random Arrays

1) Random matrix with values between 0 and 1: np.random.random(shape)
    
2) Random matrix with integer values ranging between two given fixed values: np.random.randint(start, stop, size=shape)
    
3) Random matrix with numbers draws from normal distribution: np.random.normal(mean, standard deviation, size=shape)

In [205]:
x=np.random.normal(5,2,(4,5))

In [206]:
np.mean(x)

5.581396359241524

# Exercise 7: Create an ndarray
    
Create a 7x4 array that only contain random numbers between 10 and 20 inclusive.

In [207]:
np.random.randint(10,21,(7,4))

array([[17, 18, 12, 13],
       [11, 14, 10, 17],
       [15, 16, 15, 19],
       [20, 11, 14, 14],
       [19, 15, 16, 14],
       [12, 18, 19, 15],
       [12, 11, 18, 11]])

# Exercise 8: Accessing, Deleting, and Inserting Elements into ndarrays

1) Accessing an element in 1-D Array

2) Accessing an element in 2-D Array

3) Appending: np.append(ndarray, elements, axis)

4) Deleting: np.delete(ndarray, elements, axis)

5) Inserting: np.insert(ndarray, index, elements, axis)

6) Stacking: Horizontal - np.hstack(), Vertical - np.vstack()

7) Slicing: 
    ndarray[start:end]
    nadarray[start:]
    nadarray[:end]

axis= 0 : Rows
axis= 1 : Columns

In [224]:
x=np.random.randint(1,20,(4,4))
y=np.random.randint(1,8,4)
print('This is 2D \n ',x)
print()
print('This is 1D Array', y)
print()

This is 2D 
  [[10 16 11 12]
 [18 10 13 18]
 [17 15  9 12]
 [17 17  6  6]]

This is 1D Array [6 7 4 1]



In [310]:
x=np.array([[4,8,9,21,82,22,31]])
range=np.max(x)-np.min(x)
std=np.std(x)
int(range-std)
print(int(range))

78


# Exercise 9: Data Extraction and Copying

1) Extracting diagonal elements of a matrix: np.diag(ndarray)

2) Extracting elements above and below main diagonal: np.diag(ndarray, k=value) - 
    value = positive - above main diagonal
    value = negative - below main diagonal

3) Extract unique array of values from an array or matrix: np.unique()

4) Copying: np.copy(ndarray)

In [313]:
len(np.unique(np.array([4,2,5,6,7,8,9,10,12,21,21,23,42,76,51,31,21,12,6,7,4,8,2])))

15

# Exercise 10: Boolean and Set Operations

1) Finding elements for a given boolean condition: x[x>value]

2) Use boolean indexing to assign new values to an existing array or matrix.

3) Create and sort an array: np.sort(ndarray)

4) Create and sort a rank 2 array: np.sort(ndarray, axis= 0/1)

5) Use of set operations on 1-d array: np.union1d(x,y), np.intersect1d(x,y), np.setdiff1d(x,y)


In [271]:
x=np.random.randint(1,50,(5,5))
print('original matrix, \n ',x)

original matrix, 
  [[29 35  4 16 28]
 [29 20 16 12 40]
 [21 35 31  2 12]
 [26 24 33 29 27]
 [ 1 43 22 41 43]]


In [277]:


np.setdiff1d(y,x)

array([11])

# Exercise 11: Artihmetic and Statistics Operations

1) Use the basic arithmetic operations on 1-D arrays: np.add(x,y), np.subtract(x,y), np.multiply(x,y), np.divide(x,y)

2) Use the basic mathematical operations: np.exp(x), np.sqrt(x), np.pow(x,value)

3) Use the statistical operations: np.max(), np.min(), np.mean(), np.std(), np.median()

In [284]:
x=np.array([[1,2],[4,5]])
y=np.array([[2,5],[1,2]])

x.dot(y)

array([[ 4,  9],
       [13, 30]])

In [296]:
a=np.array([5,6,7,8,9,10,21,87,32,10005])

print('Median',np.median(a))
print('Mean',np.mean(a))
print('Standard Deviation',np.std(a))
print('Range', np.max(a)-np.min(a))

Median 9.5
Mean 1019.0
Standard Deviation 2995.426580639225
Range 10000


# Exercise - 12: 

Create a 5x5 ndarray with consecutive integers from 1 to 25 inclusive. Afterwards use Boolean indexing to pick out only the odd numbers in an array.


In [302]:
X=np.arange(1,26).reshape(5,5)
print(X)

X[X%2!=0]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [315]:
x=np.array([[7,8],[9,2]])
y=np.array([[3,4],[7,1]])

print('Matrix X \n \n ', x )
print()
print()

print('Matrix Y \n \n ',y)

Matrix X 
 
  [[7 8]
 [9 2]]


Matrix Y 
 
  [[3 4]
 [7 1]]


In [319]:
np.sum((x.dot(y)))

192

In [325]:
v=np.array([5,6,7,8])
np.tile(v,(4,2))
print(np.empty_like(v))

[5 6 7 8]
