# Exercise 1: Creating Numpy Arrays

At the core of NumPy is the ndarray, where nd stands for n-dimensional. An ndarray is a multidimensional array of elements all of the same type. 

Check size, shape, type and dtype for all the below:

1) Create 1D array containing integers

2) Create 1D array containing strings

3) Create 2D array containing integers

4) Create 1D array containing float and integers - Understand Upcasting

5) Create an array and fix the dtype to int64

6) Save and load numpy array using np.save() and np.load()

https://docs.scipy.org/doc/numpy/user/basics.creation.html

In [32]:
import numpy as np

x=np.array([[2,3,4], [4,5,6], [5,6,7,9]])

In [37]:
x=np.array([3,4,5], dtype=float)

array([3., 4., 5.])

In [2]:
import numpy as np
#1-D Array containing Integers

x= np.array([6,4,7,4,2,0])
print(x)
print(x.dtype)
print(x.shape)
print(type(x))
print(x.size)
print()
print()

#1-D Array containing Strings
x= np.array(['this', 'is','a','string'])
print(x)
print(x.dtype)
print(x.shape)
print(type(x))
print(x.size)
print()
print()

#2-D Array containing Integers
x=np.array([[4,7,8],[8,9,2],[1,2,4]])
print(x)
print(x.dtype)
print(x.shape)
print(type(x))
print(x.size)
print()
print()

#1-D Array of Integers and Floats - Upcasting
x= np.array([6,4.5, 6.4,3,9])
print(x)
print(x.dtype)
print(x.shape)
print(type(x))
print(x.size)
print()
print()

#1-D Array of Integers and Floats - Upcasting
x= np.array([6,4.5, 6.4,3,9],dtype=str)
print(x)
print(x.dtype)
print(x.shape)
print(type(x))
print(x.size)
print()
print()

#Save and Load a numpy file
a=np.array([2,3,4,5,9.7])
np.save('xyz',a)
b=np.load('xyz.npy')
print(b)

[6 4 7 4 2 0]
int32
(6,)
<class 'numpy.ndarray'>
6


['this' 'is' 'a' 'string']
<U6
(4,)
<class 'numpy.ndarray'>
4


[[4 7 8]
 [8 9 2]
 [1 2 4]]
int32
(3, 3)
<class 'numpy.ndarray'>
9


[6.  4.5 6.4 3.  9. ]
float64
(5,)
<class 'numpy.ndarray'>
5


['6' '4.5' '6.4' '3' '9']
<U3
(5,)
<class 'numpy.ndarray'>
5


[2.  3.  4.  5.  9.7]


In [39]:
a=np.array([2,3,4,5,9.7])

#np.save('xyz',a)
#b=np.load('xyz.npy')
#print(b)

In [41]:
np.save('file', a)

b=np.load('file.npy')
print(b)

[2.  3.  4.  5.  9.7]


In [42]:
import os
os.getcwd()

'C:\\Users\\user\\DS Training'

# Exercise 2: Using Built-in functions to Create ndarrays

shape in the form (rows, columns)

1) Zero array or matrix - Use np.zeros(shape) 

2) array or matrix of ones - Use np.ones(shape)

3) array or matrix of specific number - Use np.full(shape, number) 

4) identity matrix - Use np.eye(matrix-size)

5) diagonal matrix - Use np.diag([list])

In [3]:
#Zero matrix
z= np.zeros((4,3))
print(z)
print()

#Matrix of ones
z=np.ones((2,3))
print(z)
print()

#Matrix of specific number
z=np.full((3,3),4)
print(z)
print()

#Identity Matrix
z=np.eye(5)
print(z)

#Diagonal Matrix
z=np.diag([4,5,6])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[4 4 4]
 [4 4 4]
 [4 4 4]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[4 0 0]
 [0 5 0]
 [0 0 6]]


# Exercise 3:

Create a 4x5 matrix with first column as ones, second as only 2's, third as 3's .. and so on. 

Sample Output: 
([[1., 2., 3., 4., 5.],
  [1., 2., 3., 4., 5.],
  [1., 2., 3., 4., 5.],
  [1., 2., 3., 4., 5.]])

In [5]:
np.ones((4,5))*np.array([1,2,3,4,5])

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

# Exercise 4: Using Built-in function - arange, linspace : To create one dimensional array

**np.arange**

np.arange() allows you to create ndarrays that have evenly spaced values within a given interval.This function is very versatile and can be used with either one, two, or three arguments. 

a) np.arange(N)

b) np.arange(start,stop)

c) np.arange(start,stop,step)

**np.linspace()**

np.linspace(start, stop, N) function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values.

np.linspace(start, stop, spacing, endpoint=True/False)

In [7]:
# Using np.arange
x=np.arange(1,26,2)
print(x)
print()

#Using np.linspace
x=np.linspace(2,26,50)
print(x)
print()

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]

[ 2.          2.48979592  2.97959184  3.46938776  3.95918367  4.44897959
  4.93877551  5.42857143  5.91836735  6.40816327  6.89795918  7.3877551
  7.87755102  8.36734694  8.85714286  9.34693878  9.83673469 10.32653061
 10.81632653 11.30612245 11.79591837 12.28571429 12.7755102  13.26530612
 13.75510204 14.24489796 14.73469388 15.2244898  15.71428571 16.20408163
 16.69387755 17.18367347 17.67346939 18.16326531 18.65306122 19.14285714
 19.63265306 20.12244898 20.6122449  21.10204082 21.59183673 22.08163265
 22.57142857 23.06122449 23.55102041 24.04081633 24.53061224 25.02040816
 25.51020408 26.        ]



# Exercise 4: Using Built-in function - reshape : To create Two dimensional array

In [9]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Exercise 5: 

Create a matrix of 6 x 4 dimensions, with each element as a multiple of 3.

sample output:

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60],
       [63, 66, 69, 72]])

In [11]:
np.arange(3,73,3).reshape(6,4)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60],
       [63, 66, 69, 72]])

# Exercise 6: Random Arrays

1) Random matrix with values between 0 and 1: np.random.random(shape)
    
2) Random matrix with integer values ranging between two given fixed values: np.random.randint(start, stop, size=shape)
    
3) Random matrix with numbers draws from normal distribution: np.random.normal(mean, standard deviation, size=shape)

In [19]:
# Random array of 1D - Values between 0 and 1
x=np.random.random(4)
print(x)
print()

# Random Matrix 2d - Values between 0 and 1
x=np.random.random((3,3))
print(x)
print()

# Random array 1D - values between given two integers
x=np.random.randint(3,7, size=5)
print(x)
print()

# Random Matrix 2D - values between given two integers
x=np.random.randint(3,7, size=(4,4))
print(x)
print()

# Random Matrix 2D - values distributed normally
x=np.random.normal(11, 1.72,size=(3,3))
print(x)
print()

[0.76998966 0.94761889 0.5029533  0.03398888]

[[0.5738655  0.7928016  0.55325703]
 [0.20498115 0.22780049 0.01620576]
 [0.21919281 0.81529144 0.88749774]]

[5 6 5 4 3]

[[5 3 3 3]
 [4 6 6 4]
 [3 3 6 5]
 [6 6 6 5]]

[[10.18543473 10.45258131  9.42279675]
 [10.91415754 13.67045066 10.44324803]
 [ 9.36196163 11.34603442 11.91479973]]



# Exercise 7: Create an ndarray
    
Create a 7x4 array that only contain random numbers between 10 and 20 inclusive.

In [23]:
np.random.randint(10,20,size=(7,4))

array([[11, 14, 19, 16],
       [19, 15, 15, 11],
       [12, 10, 13, 13],
       [16, 10, 19, 14],
       [12, 12, 16, 17],
       [17, 10, 18, 17],
       [14, 13, 13, 16]])

# Exercise 8: Accessing, Deleting, and Inserting Elements into ndarrays

1) Accessing an element in 1-D Array

2) Accessing an element in 2-D Array

3) Appending: np.append(ndarray, elements, axis)

4) Deleting: np.delete(ndarray, elements, axis)

5) Inserting: np.insert(ndarray, index, elements, axis)

6) Stacking: Horizontal - np.hstack(), Vertical - np.vstack()

7) Slicing: 
    ndarray[start:end]
    nadarray[start:]
    nadarray[:end]

axis= 0 : Rows
axis= 1 : Columns

In [63]:
a=np.array([4,3,2,1,5,7,5,4,2,1,9])
b=np.array([[3,4,7,9],[1,2,1,1],[3,2,5,6]])

#Accessing an element in 1D array
c=a[1:3]
print(c)
print()

#Accessing an element in 2D array
c=b[0:2,1:3]
print(c)

# Delete 5th element of array a
c=np.delete(a,4)
print('deleted 5th element',c)

# Delete first and last row of matrix b
c=np.delete(b, [0,2], axis=0)
print('Deleted',c)
print()

# Delete first and last row of matrix b
c=np.delete(b, [0,2], axis=0)
print('Deleted',c)
print()

# Delete first column of matrix b
c=np.delete(b, 0, axis=1)
print('Deleted Column', c)
print()

#Appending a value in array a
c=np.append(a, 0)
print(c)

#Appending a row in matrix b
c=np.append(b, [[4,3,3,3]], axis=0)
print(c)
print()

#Appending a column in matrix b
d=np.append(b, [[4],[2],[2]],axis=1)
print(d)
print()

#Inserting a value in array a
d=np.insert(a, 2, 20)
print(d)

#Inserting a row in matrix b
d=np.insert(b, 1, [1,2,1,1],axis=0)
print('Insert a row \n ', d)

#Inserting a column in matrix b
d=np.insert(b, 1, [1,1,1],axis=1)
print('Insert a column \n ', d)

#Stacking : Hstack
x=np.array([3,4,5])
y=np.array([5,5,5])
z=np.hstack((x,y))
print('Horizontal Stack \n ', z)

#Stacking : vstack
x=np.array([3,4,5])
y=np.array([5,5,5])
z=np.vstack((x,y))
print('Vertical Stack \n ', z)

#Slicing
a=b[1:3,2:4]
print(a)

[3 2]

[[4 7]
 [2 1]]
deleted 5th element [4 3 2 1 7 5 4 2 1 9]
Deleted [[1 2 1 1]]

Deleted [[1 2 1 1]]

Deleted Column [[4 7 9]
 [2 1 1]
 [2 5 6]]

[4 3 2 1 5 7 5 4 2 1 9 0]
[[3 4 7 9]
 [1 2 1 1]
 [3 2 5 6]
 [4 3 3 3]]

[[3 4 7 9 4]
 [1 2 1 1 2]
 [3 2 5 6 2]]

[ 4  3 20  2  1  5  7  5  4  2  1  9]
Insert a row 
  [[3 4 7 9]
 [1 2 1 1]
 [1 2 1 1]
 [3 2 5 6]]
Insert a column 
  [[3 1 4 7 9]
 [1 1 2 1 1]
 [3 1 2 5 6]]
Horizontal Stack 
  [3 4 5 5 5 5]
Vertical Stack 
  [[3 4 5]
 [5 5 5]]
[[1 1]
 [5 6]]


# Exercise 9: Data Extraction and Copying

1) Extracting diagonal elements of a matrix: np.diag(ndarray)

2) Extracting elements above and below main diagonal: np.diag(ndarray, k=value) - 
    value = positive - above main diagonal
    value = negative - below main diagonal

3) Extract unique array of values from an array or matrix: np.unique()

4) Copying: np.copy(ndarray)

In [69]:
b=np.array([[3,4,7,9],[1,2,1,1],[3,2,5,6],[1,1,1,1]])

# Extract Diagonal
x=np.diag(b)
print(x)
print()

# Extract Upper Diagonal
x=np.diag(b,1)
print(x)
print()

# Extract Lower Diagonal
x=np.diag(b,-1)
print(x)
print()

# Extract Unique Element
x=np.unique(b)
print(x)
print()

# Extract Unique Element
x=np.unique(b)
print(x)
print()

#Copy 

x=np.copy(b)
print(x)

[3 2 5 1]

[4 1 6]

[1 2 1]

[1 2 3 4 5 6 7 9]

[1 2 3 4 5 6 7 9]

[[3 4 7 9]
 [1 2 1 1]
 [3 2 5 6]
 [1 1 1 1]]


# Exercise 10: Boolean and Set Operations

1) Finding elements for a given boolean condition: x[x>value]

2) Use boolean indexing to assign new values to an existing array or matrix.

3) Create and sort an array: np.sort(ndarray)

4) Create and sort a rank 2 array: np.sort(ndarray, axis= 0/1)

5) Use of set operations on 1-d array: np.union1d((x,y))

In [73]:
import numpy as np
x=np.arange(50).reshape(10,5)

# Find all elements greater than 20 in the given matrix
y=x[(x>20)]
print(y)
print()

# Find all elements greater than 20 but less than or equal to 45in the given matrix
z=x[(x>20) & (x<=35)]
print(z)
print()

# Assign value -1 to elements with value greater than 5 but less than or equal to 10
x[(x>5) & (x<=10)]=-1
print(x)
print()

#Create and sort an array -Descending Order
new_array=[91,45,76,98,32,12,49]
print(np.sort(new_array)[::-1])

# Create a rank 2 array
mat=np.random.randint(1,11, size=[5,5])
print(mat)
print()

# Sort columns of mat and print
print(np.sort(mat, axis=0))
print()

# Sort rows of mat and print 
print(np.sort(mat, axis=1))
print()

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49]

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]

[[ 0  1  2  3  4]
 [ 5 -1 -1 -1 -1]
 [-1 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

[98 91 76 49 45 32 12]
[[ 6  4  4  8  3]
 [ 9  9  3  2  4]
 [ 6  9  2  1  2]
 [ 7  7  5  8  8]
 [ 1  3  5  7 10]]

[[ 1  3  2  1  2]
 [ 6  4  3  2  3]
 [ 6  7  4  7  4]
 [ 7  9  5  8  8]
 [ 9  9  5  8 10]]

[[ 3  4  4  6  8]
 [ 2  3  4  9  9]
 [ 1  2  2  6  9]
 [ 5  7  7  8  8]
 [ 1  3  5  7 10]]



In [72]:
x=np.array([1,3,5,7])
y=np.array([2,3,4,5,6,9,10])

# Union of sets
print(np.union1d(x,y))

# Intersection of sets
print(np.intersect1d(x,y))

# Difference of sets
print(np.setdiff1d(x,y))

[ 1  2  3  4  5  6  7  9 10]
[3 5]
[1 7]


# Exercise 11: Artihmetic and Statistics Operations

1) Use the basic arithmetic operations on 1-D arrays: np.add(x,y), np.subtract(x,y), np.multiply(x,y), np.divide(x,y)

2) Use the basic mathematical operations: np.exp(x), np.sqrt(x), np.pow(x,value)

3) Use the statistical operations: np.max(), np.min(), np.mean(), np.std(), np.median()

In [74]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


In [75]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


# Exercise - 12: 

Create a 5x5 ndarray with consecutive integers from 1 to 25 inclusive. Afterwards use Boolean indexing to pick out only the odd numbers in an array.



In [78]:
# Create a 5x5 array

X =np.arange(1,26).reshape(5,5) 

# Use boolean indexing to pick only odd numbers in the array

Y = X[X%2!=0]

print(Y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
