# Exercise 1:
    
Using a Text file: (test_data.txt)
    
1) Read a text file using 'r' along with open commmand.

2) Write into a text file using 'w' along open command.

3) Append text file using 'a' along with open command.

4) Reading files with Contextmanager 'with' command.

5) Checking the availability of a file using os.path.exists()

6) Remove the file from the directory using os.remove().

In [ ]:

data = open('test_data.txt', 'r') 
text = data.readlines()
data.close()

print(text)
type(text)

In [ ]:
with open('new_data.txt','w') as file:
    text=file.write('this is new file')
    


In [ ]:
with open('new_data.txt') as file:
    text = file.read()
    
text

In [2]:
import os
os.getcwd()
os.chdir('E:\Azeem\Data-Analysis-with-R-master\Data Analyis with Python')
os.getcwd()

'E:\\Azeem\\Data-Analysis-with-R-master\\Data Analyis with Python'

# Exercise 3: Write the following in a text file Using Context Manager

Jim always kept that five-center piece round his neck with a string, and said it was a charm the devil give to him with his own hands, and told him he could cure anybody with it and fetch witches whenever he wanted to just by saying something to it; but he never told what it was he said to it.  Niggers would come from all around there and give Jim anything they had, just for a sight of that five-center piece; but they wouldn’t touch it, because the devil had had his hands on it.  Jim was most ruined for a servant, because he got stuck up on account of having seen the devil and been rode by witches. 

# Exercise 4: Write a list of lines in a text file

List = ['this is first ', 'this is second', 'this is third', 'this is fourth']

# Exercise 5: Bag of Words 

Create a word list for the given document, and count the occurence of each word. 


In [6]:
with open('test_data.txt','r') as file:
    text=file.readlines()
    

    
word = []

for line in text:
    x= line.split()
    word.extend(x)

#print(word)

import collections

word_counter = collections.Counter(word)

word_counter.most_common(5)

[('and', 22), ('the', 19), ('a', 10), ('of', 5), ('went', 5)]

In [ ]:
pip install collections

# Exercise 6: Generate Key Words

For the given document,find the most frequently used words used in the document and use as key word to represent the document.

# Exercise 7: Read a Text File Using Numpy

np.loadtxt(filename, delimiter= , dtype= )

filename=test_data.txt

In [19]:
import numpy as np

a= np.loadtxt('test_data.txt',delimiter=';', dtype= str )

print(a)



['Well, when Tom and me got to the edge of the hilltop we looked away down into the village and could see three or four lights twinkling, where there was sick folks, maybe; and the stars over us was sparkling ever so fine; and down by the village was the river, a whole mile broad, and awful still and grand.  '
 'We went down the hill and found Jo Harper and Ben Rogers, and two or three more of the boys, hid in the old tanyard.  '
 'So we unhitched a skiff and pulled down the river two mile and a half, to the big scar on the hillside, and went ashore. '
 'We went to a clump of bushes, and Tom made everybody swear to keep the secret, and then showed them a hole in the hill, right in the thickest part of the bushes.  '
 'Then we lit the candles, and crawled in on our hands and knees.  '
 'We went about two hundred yards, and then the cave opened up. '
 'Tom poked about amongst the passages, and pretty soon ducked under a wall where you wouldn’t a noticed that there was a hole.  '
 'We w

# Exercise 8: Read a flat file (comma separated, tab separated) numerical data using Numpy

np.loadtxt(filename, delimiter= , dtype= )

filename=numbers.txt

In [14]:
import numpy as np

a= np.loadtxt('numbers.txt',delimiter='\t')

print(a)

a.ndim

[[10.  8.  9.  8.]
 [89.  7.  6. 71.]]


2

# Exercise 9: Read a CSV file with mixed data type in Numpy

np.recfromcsv(file)

filename=daily_engagement.csv

In [22]:
data= np.recfromcsv('daily_engagement.csv', delimiter=',')

print(data)

[(   0, b'2015-01-09', 1., 11.6793745 , 0., 0.)
 (   0, b'2015-01-10', 2., 37.28488733, 0., 0.)
 (   0, b'2015-01-11', 2., 53.63374633, 0., 0.) ...
 (1305, b'2015-06-16', 1.,  2.72013633, 0., 0.)
 (1305, b'2015-06-17', 0.,  0.        , 0., 0.)
 (1305, b'2015-06-18', 0.,  0.        , 0., 0.)]


# Exercise 10: Read a CSV/TSV file using Pandas library [Numbers]

pd.read_csv(filename, delimiter, header = None)

daily_engagement

In [26]:
import pandas as pd

data = pd.read_csv('daily_engagement.csv')

data.head()
data.tail()

account_key    utc_date  num_courses_visited  total_minutes_visited  \
136235         1305  2015-06-14                  0.0               0.000000   
136236         1305  2015-06-15                  0.0               0.000000   
136237         1305  2015-06-16                  1.0               2.720136   
136238         1305  2015-06-17                  0.0               0.000000   
136239         1305  2015-06-18                  0.0               0.000000   

        lessons_completed  projects_completed  
136235                0.0                 0.0  
136236                0.0                 0.0  
136237                0.0                 0.0  
136238                0.0                 0.0  
136239                0.0                 0.0

# Exercise 11: Read a Excel file using Pandas library [Mixed Data Types]

pd.read_excel(filename, delimiter, header = None)

or

pd.ExcelFile()

file = Orders_and_Returns.xlsx

In [37]:
import pandas as pd

data = pd.read_excel('Orders_and_Returns.xlsx', sheet_name='Orders')

data.head()

SyntaxError: invalid syntax (<ipython-input-37-6826f7336450>, line 3)

# Exercise 12: Read and Write data to a pickled file

pickle.dump(file,output)
pickle.load(file)

In [40]:
dic = {'a':6, 'b':10, 'c': 15}

import pickle

with open('some.pk1','wb') as file:
    pickle.dump(dic, file)
    


In [41]:
with open('some.pk1', 'rb') as file:
    data = pickle.load(file)

data

{'a': 6, 'b': 10, 'c': 15}

# Exercise 13: Import Data from a SAS File

Import airline.sas7bdat file.

In [43]:
import pandas as pd

from sas7bdat import SAS7BDAT

with SAS7BDAT('airline.sas7bdat') as file:
    data= file.to_data_frame()

data.head()

YEAR      Y      W       R      L      K
0  1948.0  1.214  0.243  0.1454  1.415  0.612
1  1949.0  1.354  0.260  0.2181  1.384  0.559
2  1950.0  1.569  0.278  0.3157  1.388  0.573
3  1951.0  1.948  0.297  0.3940  1.550  0.564
4  1952.0  2.265  0.310  0.3559  1.802  0.574

# Exercise 14: Import Data from Stata file

Import stata file alcohol with .dta extension

In [44]:
import pandas as pd

data = pd.read_stata('alcohol.dta')

data.head()

adults  kids  income  consume
0       2     2     758        1
1       2     3    1785        1
2       3     0    1200        1
3       1     0     545        1
4       4     1     547        1

# Exercise 15: Import Data from HDF5 file

hh5de.h5

In [49]:
import h5py
data = h5py.File('hh5de.h5','r') 


data.keys()

data['DS1']

data['DS2']

<HDF5 dataset "DS2": shape (4, 7), type "<i4">

# Exercise 16: Import data from a .mat file (MATLAB
                                           
Import new.mat

In [55]:
import scipy.io

data = scipy.io.loadmat('new.mat')

type(data)

data['y']

array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)