In [1]:
import os
os.chdir('E:\Azeem\Data-Analysis-with-R-master\Data Analyis with Python')

# Exercise 1:
    
Using a Text file: (test_data.txt)
    
1) Read a text file using 'r' along with open commmand.

2) Write into a text file using 'w' along open command.

3) Append text file using 'a' along with open command.

4) Reading files with Contextmanager 'with' command.

5) Checking the availability of a file using os.path.exists()

6) Remove the file from the directory using os.remove().

In [30]:
#Reading a text file

data=open ('test_data.txt','r')
text=data.read()
data.close()
print(text)

Well, when Tom and me got to the edge of the hilltop we looked away down into the village and could see three or four lights twinkling, where there was sick folks, maybe; and the stars over us was sparkling ever so fine; and down by the village was the river, a whole mile broad, and awful still and grand.  
We went down the hill and found Jo Harper and Ben Rogers, and two or three more of the boys, hid in the old tanyard.  
So we unhitched a skiff and pulled down the river two mile and a half, to the big scar on the hillside, and went ashore. 
We went to a clump of bushes, and Tom made everybody swear to keep the secret, and then showed them a hole in the hill, right in the thickest part of the bushes.  
Then we lit the candles, and crawled in on our hands and knees.  
We went about two hundred yards, and then the cave opened up. 
Tom poked about amongst the passages, and pretty soon ducked under a wall where you wouldn’t a noticed that there was a hole.  
We went along a narrow plac

In [31]:
#Writing and appending to a text file

data=open ('some_file.txt','w')
text=data.write('what is this? \n ')
data.close()

data=open ('some_file.txt','a')
text=data.write('this is new \n ')
data.close()

In [33]:
new=open('some_file.txt','r')
tex=new.read()
new.close()
print(tex)


what is this? 
 this is new 
 


# Exercise 3: Write the following in a text file Using Context Manager

Jim always kept that five-center piece round his neck with a string, and said it was a charm the devil give to him with his own hands, and told him he could cure anybody with it and fetch witches whenever he wanted to just by saying something to it; but he never told what it was he said to it.  Niggers would come from all around there and give Jim anything they had, just for a sight of that five-center piece; but they wouldn’t touch it, because the devil had had his hands on it.  Jim was most ruined for a servant, because he got stuck up on account of having seen the devil and been rode by witches. 

In [48]:
#Use Context Manager : With

with open('new_data.txt','w') as file:
    file.write('Jim always kept that five-center piece round his neck with a string, and said it was a charm the devil give to him with his own hands, and told him he could cure anybody with it and fetch witches whenever he wanted to just by saying something to it; but he never told what it was he said to it.  Niggers would come from all around there and give Jim anything they had, just for a sight of that five-center piece; but they wouldn’t touch it, because the devil had had his hands on it.  Jim was most ruined for a servant, because he got stuck up on account of having seen the devil and been rode by witches.')

new=open('new_data.txt','r')
tex=new.read()
new.close()
print(tex)


Jim always kept that five-center piece round his neck with a string, and said it was a charm the devil give to him with his own hands, and told him he could cure anybody with it and fetch witches whenever he wanted to just by saying something to it; but he never told what it was he said to it.  Niggers would come from all around there and give Jim anything they had, just for a sight of that five-center piece; but they wouldn’t touch it, because the devil had had his hands on it.  Jim was most ruined for a servant, because he got stuck up on account of having seen the devil and been rode by witches.


# Exercise 4: Write a list of lines in a text file

List = ['this is first ', 'this is second', 'this is third', 'this is fourth']

In [49]:
lst = ['this is first \n ', 'this is second \n ', 'this is third \n ', 'this is fourth \n ']

data=open ('new_file.txt','w')
text=data.writelines(lst)
data.close()

In [50]:
data=open ('new_file.txt','r')
text=data.read()
data.close()
print(text)

this is first 
 this is second 
 this is third 
 this is fourth 
 


# Exercise 5: Bag of Words 

Create a word list for the given document, and count the occurence of each word. 



In [61]:
data=open ('test_data.txt','r')
text=data.readlines()
data.close()
#print(text)

x=[]
for line in text:
    z=line.split()
    x.extend(z)

x

import collections
raw=collections.Counter(x)
print(raw)

Counter({'and': 22, 'the': 19, 'a': 10, 'of': 5, 'went': 5, 'to': 4, 'we': 4, 'down': 4, 'was': 4, 'We': 4, 'in': 4, 'Tom': 3, 'there': 3, 'two': 3, 'got': 2, 'into': 2, 'village': 2, 'three': 2, 'or': 2, 'where': 2, 'mile': 2, 'on': 2, 'then': 2, 'about': 2, 'Well,': 1, 'when': 1, 'me': 1, 'edge': 1, 'hilltop': 1, 'looked': 1, 'away': 1, 'could': 1, 'see': 1, 'four': 1, 'lights': 1, 'twinkling,': 1, 'sick': 1, 'folks,': 1, 'maybe;': 1, 'stars': 1, 'over': 1, 'us': 1, 'sparkling': 1, 'ever': 1, 'so': 1, 'fine;': 1, 'by': 1, 'river,': 1, 'whole': 1, 'broad,': 1, 'awful': 1, 'still': 1, 'grand.': 1, 'hill': 1, 'found': 1, 'Jo': 1, 'Harper': 1, 'Ben': 1, 'Rogers,': 1, 'more': 1, 'boys,': 1, 'hid': 1, 'old': 1, 'tanyard.': 1, 'So': 1, 'unhitched': 1, 'skiff': 1, 'pulled': 1, 'river': 1, 'half,': 1, 'big': 1, 'scar': 1, 'hillside,': 1, 'ashore.': 1, 'clump': 1, 'bushes,': 1, 'made': 1, 'everybody': 1, 'swear': 1, 'keep': 1, 'secret,': 1, 'showed': 1, 'them': 1, 'hole': 1, 'hill,': 1, 'right

# Exercise 6: Generate Key Words

For the given document,find the most frequently used words used in the document and use as key word to represent the document.

In [71]:
#Use Context Manager : With

with open('new_data.txt','r') as file:
    data=file.readlines()

x=[]
for line in data:
    line.replace('\n',' ')
    z=line.split()
    x.extend(z)

import collections
raw=collections.Counter(x)
keywords=raw.most_common(4)
print(keywords)

[('and', 5), ('he', 5), ('a', 4), ('to', 4)]


# Exercise 7: Read a Text File Using Numpy

np.loadtxt(filename, delimiter= , dtype= )

filename=test_data.txt

In [4]:
import numpy as np
file='test_data.txt'
data=np.loadtxt(file,delimiter='\t',dtype=str)

#Converting list to string
new=' '.join(data)
print(new)

Well, when Tom and me got to the edge of the hilltop we looked away down into the village and could see three or four lights twinkling, where there was sick folks, maybe; and the stars over us was sparkling ever so fine; and down by the village was the river, a whole mile broad, and awful still and grand.   We went down the hill and found Jo Harper and Ben Rogers, and two or three more of the boys, hid in the old tanyard.   So we unhitched a skiff and pulled down the river two mile and a half, to the big scar on the hillside, and went ashore.  We went to a clump of bushes, and Tom made everybody swear to keep the secret, and then showed them a hole in the hill, right in the thickest part of the bushes.   Then we lit the candles, and crawled in on our hands and knees.   We went about two hundred yards, and then the cave opened up.  Tom poked about amongst the passages, and pretty soon ducked under a wall where you wouldn’t a noticed that there was a hole.   We went along a narrow plac

# Exercise 8: Read a flat file (comma separated, tab separated) numerical data using Numpy

np.loadtxt(filename, delimiter= , dtype= )

filename=numbers.txt

In [5]:
import numpy as np

data=np.loadtxt('numbers.txt',delimiter=',')
print(data)

[[10.  5.  6.  7.  7.  7.]
 [ 4.  5.  6.  7.  8.  4.]]


# Exercise 9: Read a CSV file with mixed data type in Numpy

np.recfromcsv(file)

filename=daily_engagement.csv

In [80]:

file='daily_engagement.csv'
a=np.recfromcsv(file)
a


rec.array([(   0, b'2015-01-09', 1., 11.6793745 , 0., 0.),
           (   0, b'2015-01-10', 2., 37.28488733, 0., 0.),
           (   0, b'2015-01-11', 2., 53.63374633, 0., 0.), ...,
           (1305, b'2015-06-16', 1.,  2.72013633, 0., 0.),
           (1305, b'2015-06-17', 0.,  0.        , 0., 0.),
           (1305, b'2015-06-18', 0.,  0.        , 0., 0.)],
          dtype=[('account_key', '<i4'), ('utc_date', 'S10'), ('num_courses_visited', '<f8'), ('total_minutes_visited', '<f8'), ('lessons_completed', '<f8'), ('projects_completed', '<f8')])

# Exercise 10: Read a CSV/TSV file using Pandas library [Numbers]

pd.read_csv(filename, delimiter, header = None)

In [82]:
import pandas as pd
a=pd.read_csv('numbers.txt',delimiter=',',header=None, )
a

0  1  2  3  4  5
0  10  5  6  7  7  7
1   4  5  6  7  8  4

# Exercise 10: Read a CSV/TSV file using Pandas library [Mixed Data Types]

pd.read_csv(filename, delimiter, header = None)
file = daily_engagement

In [ ]:
import pandas as pd
data=pd.read_csv('daily_engagement.csv')
data.head()

# Exercise 11: Read a Excel file using Pandas library [Mixed Data Types]

pd.read_excel(filename, delimiter, header = None)

or

pd.ExcelFile()

file = Orders_and_Returns.xlsx

In [ ]:
#Importing Excel file using Pd.ExcelFile

import pandas as pd
data=pd.ExcelFile('Orders_and_Returns.xlsx')
data.sheet_names

df1=data.parse(0)
df1.head()

In [8]:
# Read Excel file using pd.read_excel
import pandas as pd

data=pd.read_excel('Orders_and_Returns.xlsx',sheet_name='Returns',use_cols=['Status'])

data.head()

Order ID    Status
0        65  Returned
1       612  Returned
2       614  Returned
3       678  Returned
4       710  Returned

# Exercise 12: Read and Write data to a pickled file

pickle.dump(file,output)
pickle.load(file)

In [94]:
import pickle
names_dict= {'File':8,'Manager':10, 'Windows':'7'}
filename = 'names.pk1'

output=open(filename, 'wb')
pickle.dump(names_dict, output)
output.close()

In [95]:
infile=open(filename,'rb')
new=pickle.load(infile)
infile.close()

print(new)

{'File': 8, 'Manager': 10, 'Windows': '7'}


# Exercise 13: Import Data from a SAS File

Import airline.sas7bdat file.

In [14]:
from sas7bdat import SAS7BDAT

with SAS7BDAT('airline.sas7bdat') as file:
    data=file.to_data_frame()

data.head()

YEAR      Y      W       R      L      K
0  1948.0  1.214  0.243  0.1454  1.415  0.612
1  1949.0  1.354  0.260  0.2181  1.384  0.559
2  1950.0  1.569  0.278  0.3157  1.388  0.573
3  1951.0  1.948  0.297  0.3940  1.550  0.564
4  1952.0  2.265  0.310  0.3559  1.802  0.574

# Exercise 14: Import Data from Stata file

Import stata file alcohol with .dta extension.

In [15]:
import pandas as pd

data=pd.read_stata('alcohol.dta')
data.head()

adults  kids  income  consume
0       2     2     758        1
1       2     3    1785        1
2       3     0    1200        1
3       1     0     545        1
4       4     1     547        1

# Exercise 15: Import Data from HDF5 file

hh5de.h5

In [26]:
import h5py

data=h5py.File('hh5de.h5','r')
type(data)

data.keys()

data[('DS1')].value

array([[ 0, -1, -2, -3, -4, -5, -6],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  2,  4,  6,  8, 10, 12]])

# Exercise 16: Import data from a .mat file (MATLAB)

In [11]:
import scipy.io
import pandas as pd

file = scipy.io.loadmat('new.mat')
type(file)



dict